### ISSUE TITLE
how to classify the trails

### ISSUE THREAD

**Issue by brigittegs** [jh-chung/mp3#3]

**Comment by brigittegs** [comment]
total elevation change / trail length

**Comment by brigittegs** [comment]
trail length / max trail length + elevation change / max elevation change = "points" of the trail, the more points = the hardest trail

**Comment by brigittegs** [comment]
Elevation Gain x 2 x distance (in miles). The product's square root is the numerical rating. 

For example, a 10-mile hike that gains 2,200 feet in elevation:
2,200 x 2=4,400 
4,400 x 10 = 44,000
Square root of 44,000=209.8

**Comment by jh-chung** [comment]
solved it, take a look at the code.
